<section class="mt-3 card card-body">
    <h1>Editar Categoria</h1>

    <div class="row">
        <div class="col">
            <form action="" method="POST">
                <label for="nome">Nome</label>
                <input name="nome" type="text" id="nome" class="form-control mb-3" value="<?php echo $dados[0]->nome; ?>">

                <label for="email">Email</label>
                <input name="email" type="text" id="email" class="form-control mb-3" value="<?php echo $dados[0]->email; ?>">

                <label for="perfil">Perfil</label>
                <input name="perfil" type="text" id="perfil" class="form-control mb-3" value="<?php echo $dados[0]->perfil; ?>">

                <button class="btn btn-primary">Editar</button>

            </form>
        </div>
    </div>
</section>