<section class="mt-3 card card-body">
    <h1>Editar Categoria</h1>

    <div class="row">
        <div class="col">
            <form action="" method="POST">
                <label for="nome">Nome</label>
                <input name="nome" type="text" id="nome" class="form-control mb-3" value="<?php echo $dados[0]->nome; ?>">

                <label for="vagas">Vagas</label>
                <input name="vagas" type="text" id="vagas" class="form-control mb-3" value="<?php echo $dados[0]->vagas; ?>">

                <label for="localidade">Localidade</label>
                <input name="localidade" type="text" id="localidade" class="form-control mb-3" value="<?php echo $dados[0]->localidade; ?>">

                <button class="btn btn-primary">Editar</button>

            </form>
        </div>
    </div>
</section>