<?php 
    $aluno = $dados[0];
?>
<section class="mt-3 card card-body">
    <h1>Editar Aluno</h1>

    <div class="row">
        <div class="col">
            <form action="" method="POST">
                <label for="nome">Nome</label>
                <input name="nome" type="text" id="nome" class="form-control mb-3" value="<?php echo $aluno->nome; ?>">

                <label for="matricula">Matricula</label>
                <input name="matricula" type="text" id="matricula" class="form-control mb-3" value="<?php echo $aluno->matricula; ?>">

                <label for="cpf">CPF</label>
                <input name="cpf" type="text" id="cpf" class="form-control mb-3" value="<?php echo $aluno->cpf; ?>">

                <label for="email">Email</label>
                <input name="email" type="text" id="email" class="form-control mb-3" value="<?php echo $aluno->email; ?>">

                <button class="btn btn-primary">Pronto</button>
            </form>
        </div>
        <div class="col"></div>
    </div>
</section>